import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Trash2, CheckCircle2, Pencil, CalendarDays } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/projects")({ head:()=>({meta:[{title:"Projects — STO Command Center"}]}), component:Page });

function Page(){
 const qc=useQueryClient(); const [name,setName]=useState(""); const [description,setDescription]=useState(""); const [characterId,setCharacterId]=useState(""); const [taskText,setTaskText]=useState<Record<string,string>>({}); const [editing,setEditing]=useState<any>(null);
 const chars=useQuery({queryKey:["project-characters"],queryFn:async()=>{const {data,error}=await supabase.from("characters").select("id,name").order("name");if(error)throw error;return data??[];}});
 const projects=useQuery({queryKey:["projects"],queryFn:async()=>{const {data,error}=await supabase.from("projects" as never).select("*,characters(name),project_tasks(*)").order("updated_at",{ascending:false});if(error)throw error;return data??[];}});
 const add=useMutation({mutationFn:async()=>{const {error}=await supabase.from("projects" as never).insert({name:name.trim(),description:description.trim()||null,character_id:characterId||null});if(error)throw error;},onSuccess:()=>{setName("");setDescription("");setCharacterId("");qc.invalidateQueries({queryKey:["projects"]});toast.success("Project created");},onError:(e:Error)=>toast.error(e.message)});
 const addTask=useMutation({mutationFn:async({projectId,title}:{projectId:string;title:string})=>{const {error}=await supabase.from("project_tasks" as never).insert({project_id:projectId,title:title.trim()});if(error)throw error;},onSuccess:(_,v)=>{setTaskText(s=>({...s,[v.projectId]:""}));qc.invalidateQueries({queryKey:["projects"]});},onError:(e:Error)=>toast.error(e.message)});
 const toggle=useMutation({mutationFn:async(t:any)=>{const {error}=await supabase.from("project_tasks" as never).update({done:!t.done}).eq("id",t.id);if(error)throw error;},onSuccess:()=>qc.invalidateQueries({queryKey:["projects"]})});
 const update=useMutation({mutationFn:async(p:any)=>{const {error}=await supabase.from("projects" as never).update({name:p.name.trim(),description:p.description?.trim()||null,status:p.status,priority:p.priority,target_date:p.target_date||null}).eq("id",p.id);if(error)throw error;},onSuccess:()=>{setEditing(null);qc.invalidateQueries({queryKey:["projects"]});toast.success("Project updated");},onError:(e:Error)=>toast.error(e.message)});
 const del=useMutation({mutationFn:async(id:string)=>{const {error}=await supabase.from("projects" as never).delete().eq("id",id);if(error)throw error;},onSuccess:()=>qc.invalidateQueries({queryKey:["projects"]})});
 return <AppShell title="Projects" subtitle="Goals, grinds and long-term operations"><div className="space-y-5">
 <div><p className="lcars-label">Mission control</p><h2 className="font-display text-2xl text-primary">Project Tracker</h2><p className="mt-2 text-sm text-muted-foreground">Keep ship builds, reputation grinds, upgrade plans and campaign goals in one place.</p></div>
 <Card><CardHeader><CardTitle className="text-base">New project</CardTitle></CardHeader><CardContent><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-[1fr_1fr_1fr_auto]"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Project name"/><Input value={description} onChange={e=>setDescription(e.target.value)} placeholder="What are you working towards?"/><select value={characterId} onChange={e=>setCharacterId(e.target.value)} className="h-9 rounded-md border bg-background px-2 text-sm"><option value="">No captain assigned</option>{(chars.data||[]).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><Button disabled={!name.trim()||add.isPending} onClick={()=>add.mutate()}><Plus className="mr-1 h-4 w-4"/>Create</Button></div></CardContent></Card>
 <div className="grid gap-4 md:grid-cols-2">{(projects.data as any[]||[]).map(p=>{const tasks=p.project_tasks||[];const done=tasks.filter((t:any)=>t.done).length;const progress=tasks.length?Math.round(done/tasks.length*100):p.progress;return <Card key={p.id} className="border-primary/20"><CardHeader><div className="flex items-start justify-between gap-2"><div><CardTitle className="text-base">{p.name}</CardTitle>{p.characters?.name&&<p className="mt-1 text-xs text-muted-foreground">{p.characters.name}</p>}</div><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={()=>setEditing({...p})}><Pencil className="h-4 w-4"/></Button><Button variant="ghost" size="icon" onClick={()=>del.mutate(p.id)}><Trash2 className="h-4 w-4"/></Button></div></div></CardHeader><CardContent><p className="text-sm text-muted-foreground">{p.description||"No description yet."}</p><div className="mt-4"><div className="mb-1 flex justify-between text-xs"><span>Progress</span><span>{progress}%</span></div><div className="h-2 overflow-hidden rounded bg-muted"><div className="h-full bg-primary transition-all" style={{width:progress+"%"}}/></div></div><div className="mt-4 flex gap-2"><Input value={taskText[p.id]||""} onChange={e=>setTaskText(s=>({...s,[p.id]:e.target.value}))} onKeyDown={e=>{if(e.key==="Enter"&&(taskText[p.id]||"").trim())addTask.mutate({projectId:p.id,title:taskText[p.id]})}} placeholder="Add a task…"/><Button size="icon" disabled={!(taskText[p.id]||"").trim()} onClick={()=>addTask.mutate({projectId:p.id,title:taskText[p.id]})}><Plus className="h-4 w-4"/></Button></div><div className="mt-2 space-y-1">{tasks.slice(0,8).map((t:any)=><button key={t.id} onClick={()=>toggle.mutate(t)} className="flex w-full items-center gap-2 rounded px-2 py-1 text-left text-sm hover:bg-muted">{t.done?<CheckCircle2 className="h-4 w-4 text-primary"/>:<span className="h-4 w-4 rounded-full border"/>}<span className={t.done?"line-through text-muted-foreground":""}>{t.title}</span></button>)}</div></CardContent></Card>})}</div>
 {editing&&<Card><CardHeader><CardTitle className="text-base">Edit project</CardTitle></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2">
 <Input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} placeholder="Project name"/>
 <Input value={editing.description||""} onChange={e=>setEditing({...editing,description:e.target.value})} placeholder="Description"/>
 <select value={editing.status||"active"} onChange={e=>setEditing({...editing,status:e.target.value})} className="h-9 rounded-md border bg-background px-2 text-sm"><option value="active">Active</option><option value="paused">Paused</option><option value="complete">Complete</option><option value="archived">Archived</option></select>
 <select value={editing.priority||"normal"} onChange={e=>setEditing({...editing,priority:e.target.value})} className="h-9 rounded-md border bg-background px-2 text-sm"><option value="low">Low priority</option><option value="normal">Normal priority</option><option value="high">High priority</option><option value="critical">Critical priority</option></select>
 <div className="flex items-center gap-2"><CalendarDays className="size-4 text-muted-foreground"/><Input type="date" value={editing.target_date||""} onChange={e=>setEditing({...editing,target_date:e.target.value||null})}/></div>
 </div><div className="mt-3 flex justify-end gap-2"><Button variant="ghost" onClick={()=>setEditing(null)}>Cancel</Button><Button disabled={!editing.name.trim()||update.isPending} onClick={()=>update.mutate(editing)}>Save changes</Button></div></CardContent></Card>}
 {!projects.isLoading&&!(projects.data as any[])?.length&&<div className="panel p-8 text-center text-sm text-muted-foreground">No projects yet. Create your first fleet operation above.</div>}
 </div></AppShell>
}