import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";

export function GroundBuildSection({ buildId }: { buildId: string }) {
  const qc=useQueryClient(); const [slot,setSlot]=useState("Primary Weapon"); const [equipmentId,setEquipmentId]=useState("");
  const ground=useQuery({queryKey:["ground_build",buildId],queryFn:async()=>{const {data,error}=await supabase.from("build_ground_loadouts" as never).select("*").eq("build_id",buildId).order("created_at");if(error)throw error;return data??[];}});
  const build=useQuery({queryKey:["ground_build_character",buildId],queryFn:async()=>{const {data,error}=await supabase.from("builds").select("character_id").eq("id",buildId).single();if(error)throw error;return data as any;}});
  const items=useQuery({queryKey:["ground_equipment",build.data?.character_id],enabled:!!build.data?.character_id,queryFn:async()=>{const {data,error}=await supabase.from("equipment_items" as never).select("*").eq("character_id",build.data.character_id).order("name");if(error)throw error;return data??[];}});
  const active:any=(ground.data as any[]||[])[0];
  const assigned=useQuery({queryKey:["ground_slots",active?.id],enabled:!!active?.id,queryFn:async()=>{const {data,error}=await supabase.from("ground_loadout_equipment" as never).select("*,equipment_items(*)").eq("loadout_id",active.id);if(error)throw error;return data??[];}});
  const create=useMutation({mutationFn:async()=>{const {data:u}=await supabase.auth.getUser();if(!u.user)throw new Error("Not signed in");const {error}=await supabase.from("build_ground_loadouts" as never).insert({user_id:u.user.id,build_id:buildId,name:"Ground Setup",is_active:true});if(error)throw error;},onSuccess:()=>{qc.invalidateQueries({queryKey:["ground_build",buildId]});toast.success("Ground build created");}});
  const add=useMutation({mutationFn:async()=>{if(!active?.id||!equipmentId)throw new Error("Choose ground equipment");const {error}=await supabase.from("ground_loadout_equipment" as never).upsert({loadout_id:active.id,equipment_item_id:equipmentId,slot},{onConflict:"loadout_id,slot"});if(error)throw error;},onSuccess:()=>{qc.invalidateQueries({queryKey:["ground_slots",active?.id]});setEquipmentId("");}});
  const options=useMemo(()=>((items.data as any[])||[]).filter((x:any)=>{const c=String(x.category||"").toLowerCase();return c.includes("ground")||c.includes("armor")||c.includes("kit")||c.includes("weapon")||c.includes("device");}),[items.data]);
  return <section className="mt-4 rounded-lg border border-border/70 bg-background/30 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="lcars-label">Ground build</p><p className="text-xs text-muted-foreground">Ground weapons, armor, kit modules and devices are tracked separately from the ship space build.</p></div>{!active&&<Button size="sm" variant="outline" onClick={()=>create.mutate()}>Create ground build</Button>}</div>{active&&<><div className="mt-3 flex flex-wrap gap-2"><select value={slot} onChange={e=>setSlot(e.target.value)} className="h-9 rounded-md border bg-background px-2 text-xs"><option>Primary Weapon</option><option>Secondary Weapon</option><option>Armor</option><option>Kit</option><option>Kit Module 1</option><option>Kit Module 2</option><option>Kit Module 3</option><option>Kit Module 4</option><option>Kit Module 5</option><option>Device 1</option><option>Device 2</option><option>Device 3</option><option>Device 4</option></select><select value={equipmentId} onChange={e=>setEquipmentId(e.target.value)} className="h-9 min-w-[12rem] flex-1 rounded-md border bg-background px-2 text-xs"><option value="">Select ground equipment</option>{options.map((x:any)=><option key={x.id} value={x.id}>{x.name}{x.mark_level?" — Mk "+x.mark_level:""}{x.rarity?" • "+x.rarity:""}</option>)}</select><Button size="sm" onClick={()=>add.mutate()} disabled={!equipmentId}>Assign</Button></div><div className="mt-3 space-y-1">{(assigned.data as any[]||[]).map((x:any)=><div key={x.id} className="flex items-center justify-between rounded border px-2 py-1.5 text-sm"><span>{x.slot} — {x.equipment_items?.name}</span><Button size="sm" variant="ghost" onClick={async()=>{const {error}=await supabase.from("ground_loadout_equipment" as never).delete().eq("id",x.id);if(!error)qc.invalidateQueries({queryKey:["ground_slots",active.id]});}}>Remove</Button></div>)}</div></>}</section>;
}
