import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Search, Trash2 } from "lucide-react";

export function GroundBuildSection({ buildId }: { buildId: string }) {
  const qc=useQueryClient(); const [slot,setSlot]=useState("Primary Weapon"); const [equipmentId,setEquipmentId]=useState("");
  const ground=useQuery({queryKey:["ground_build",buildId],queryFn:async()=>{const {data,error}=await supabase.from("build_ground_loadouts" as never).select("*").eq("build_id",buildId).order("created_at");if(error)throw error;return data??[];}});
  const build=useQuery({queryKey:["ground_build_character",buildId],queryFn:async()=>{const {data,error}=await supabase.from("builds").select("character_id").eq("id",buildId).single();if(error)throw error;return data as any;}});
  const items=useQuery({queryKey:["ground_equipment",build.data?.character_id],enabled:!!build.data?.character_id,queryFn:async()=>{const {data,error}=await supabase.from("equipment_items" as never).select("*").eq("character_id",build.data.character_id).order("name");if(error)throw error;return data??[];}});
  const active:any=(ground.data as any[]||[])[0];
  const [traitSearch,setTraitSearch]=useState("");
  const groundTraits=useQuery({queryKey:["ground_trait_catalog"],queryFn:async()=>{const {data,error}=await supabase.from("trait_catalog" as never).select("id,name,trait_type,domain,trait_category,description").eq("domain","ground").order("name");if(error)throw error;return data??[];}});
  const characterTraits=useQuery({queryKey:["ground_character_traits",build.data?.character_id],enabled:!!build.data?.character_id,queryFn:async()=>{const {data,error}=await supabase.from("character_traits" as never).select("id,trait_id,domain,trait_category,slot_index,active,trait_catalog(id,name,trait_type,domain,trait_category,description)").eq("character_id",build.data.character_id).eq("domain","ground").eq("active",true).order("slot_index").order("created_at");if(error)throw error;return data??[];}});
  const filteredGroundTraits=useMemo(()=>((groundTraits.data as any[])||[]).filter((t:any)=>{const q=traitSearch.trim().toLowerCase();return !q||[t.name,t.trait_type,t.trait_category,t.description].filter(Boolean).join(" ").toLowerCase().includes(q);}),[groundTraits.data,traitSearch]);
  const addGroundTrait=useMutation({mutationFn:async(trait:any)=>{const {data:u}=await supabase.auth.getUser();if(!u.user||!build.data?.character_id)throw new Error("Character is not available");if(((characterTraits.data as any[])||[]).some((x:any)=>x.trait_id===trait.id))throw new Error("That ground trait is already assigned");const nextSlot=((characterTraits.data as any[])||[]).reduce((max:number,x:any)=>Math.max(max,Number(x.slot_index)||0),0)+1;const {error}=await supabase.from("character_traits" as never).insert({user_id:u.user.id,character_id:build.data.character_id,trait_id:trait.id,domain:"ground",trait_category:trait.trait_category||trait.trait_type||"personal",slot_group:"ground",slot_index:nextSlot,active:true,source_type:"catalog",source_name:trait.name});if(error)throw error;},onSuccess:()=>{qc.invalidateQueries({queryKey:["ground_character_traits",build.data?.character_id]});toast.success("Ground trait added to character");},onError:(e:any)=>toast.error(e?.message||"Could not add ground trait")});
  const removeGroundTrait=useMutation({mutationFn:async(id:string)=>{const {error}=await supabase.from("character_traits" as never).update({active:false}).eq("id",id);if(error)throw error;},onSuccess:()=>{qc.invalidateQueries({queryKey:["ground_character_traits",build.data?.character_id]});toast.success("Ground trait removed");}});

  const assigned=useQuery({queryKey:["ground_slots",active?.id],enabled:!!active?.id,queryFn:async()=>{const {data,error}=await supabase.from("ground_loadout_equipment" as never).select("*,equipment_items(*)").eq("loadout_id",active.id);if(error)throw error;return data??[];}});
  const create=useMutation({mutationFn:async()=>{const {data:u}=await supabase.auth.getUser();if(!u.user)throw new Error("Not signed in");const {error}=await supabase.from("build_ground_loadouts" as never).insert({user_id:u.user.id,build_id:buildId,name:"Ground Setup",is_active:true});if(error)throw error;},onSuccess:()=>{qc.invalidateQueries({queryKey:["ground_build",buildId]});toast.success("Ground build created");}});
  const add=useMutation({mutationFn:async()=>{if(!active?.id||!equipmentId)throw new Error("Choose ground equipment");const {error}=await supabase.from("ground_loadout_equipment" as never).upsert({loadout_id:active.id,equipment_item_id:equipmentId,slot},{onConflict:"loadout_id,slot"});if(error)throw error;},onSuccess:()=>{qc.invalidateQueries({queryKey:["ground_slots",active?.id]});setEquipmentId("");}});
  const options=useMemo(()=>((items.data as any[])||[]).filter((x:any)=>{const c=String(x.category||"").toLowerCase();return c.includes("ground")||c.includes("armor")||c.includes("kit")||c.includes("weapon")||c.includes("device");}),[items.data]);
  return <section className="mt-4 rounded-lg border border-border/70 bg-background/30 p-3">
    <div className="flex flex-wrap items-center justify-between gap-2"><div><p className="lcars-label">Ground build</p><p className="text-xs text-muted-foreground">Ground weapons, armor, kit modules, devices and captain Ground traits are tracked separately from the ship space build.</p></div>{!active&&<Button size="sm" variant="outline" onClick={()=>create.mutate()}>Create ground build</Button>}</div>
    {active&&<><div className="mt-3 flex flex-wrap gap-2"><select value={slot} onChange={e=>setSlot(e.target.value)} className="h-9 rounded-md border bg-background px-2 text-xs"><option>Primary Weapon</option><option>Secondary Weapon</option><option>Armor</option><option>Kit</option><option>Kit Module 1</option><option>Kit Module 2</option><option>Kit Module 3</option><option>Kit Module 4</option><option>Kit Module 5</option><option>Device 1</option><option>Device 2</option><option>Device 3</option><option>Device 4</option></select><select value={equipmentId} onChange={e=>setEquipmentId(e.target.value)} className="h-9 min-w-[12rem] flex-1 rounded-md border bg-background px-2 text-xs"><option value="">Select ground equipment</option>{options.map((x:any)=><option key={x.id} value={x.id}>{x.name}{x.mark_level?" — Mk "+x.mark_level:""}{x.rarity?" • "+x.rarity:""}</option>)}</select><Button size="sm" onClick={()=>add.mutate()} disabled={!equipmentId}>Assign</Button></div>
    <div className="mt-3 space-y-1">{(assigned.data as any[]||[]).map((x:any)=><div key={x.id} className="flex items-center justify-between rounded border px-2 py-1.5 text-sm"><span>{x.slot} — {x.equipment_items?.name}</span><Button size="sm" variant="ghost" onClick={async()=>{const {error}=await supabase.from("ground_loadout_equipment" as never).delete().eq("id",x.id);if(!error)qc.invalidateQueries({queryKey:["ground_slots",active.id]});}}>Remove</Button></div>)}</div>
    <div className="mt-4 rounded-lg border border-accent/20 bg-accent/5 p-3"><div className="flex items-center justify-between gap-2"><div><p className="text-xs font-semibold uppercase tracking-wider text-accent">Ground traits</p><p className="text-[11px] text-muted-foreground">Search the Ground trait catalogue and assign traits to this character.</p></div><span className="text-[11px] text-muted-foreground">{((characterTraits.data as any[])||[]).length} assigned</span></div>
      <div className="relative mt-2"><Search className="absolute left-2 top-2 size-4 text-muted-foreground"/><Input value={traitSearch} onChange={e=>setTraitSearch(e.target.value)} placeholder="Search ground traits, category or description…" className="h-8 pl-8"/></div>
      <div className="mt-2 max-h-52 space-y-1 overflow-y-auto">{filteredGroundTraits.slice(0,50).map((t:any)=><div key={t.id} className="flex items-center justify-between gap-2 rounded border border-border/70 px-2 py-1.5"><div className="min-w-0"><p className="truncate text-xs">{t.name}</p><p className="truncate text-[10px] text-muted-foreground">{t.trait_category||t.trait_type||"Ground"}{t.description?" • "+t.description:""}</p></div><Button size="sm" variant="outline" disabled={((characterTraits.data as any[])||[]).some((x:any)=>x.trait_id===t.id)||addGroundTrait.isPending} onClick={()=>addGroundTrait.mutate(t)}>Add</Button></div>)}{!filteredGroundTraits.length&&<p className="py-3 text-center text-xs text-muted-foreground">No ground traits match your search.</p>}</div>
      <div className="mt-3 space-y-1">{((characterTraits.data as any[])||[]).map((t:any)=><div key={t.id} className="flex items-center justify-between rounded border px-2 py-1.5 text-xs"><span>{t.trait_catalog?.name||"Unnamed ground trait"}{t.slot_index!=null?" • Slot "+t.slot_index:""}</span><Button size="icon" variant="ghost" className="size-7" onClick={()=>removeGroundTrait.mutate(t.id)}><Trash2 className="size-3.5"/></Button></div>)}</div>
    </div></>}</section>;